### PR TITLE
Simplify e2e scripts & support contour

### PR DESCRIPTION
**Pull request by dprotaso**
- drop chaosduck
- drop extra gateway folder
- simplify e2e scripts - add support for contour

Fixes: https://github.com/knative-sandbox/net-gateway-api/issues/309
Fixes: https://github.com/knative-sandbox/net-gateway-api/issues/322

### CODE REVIEW

**Comment by dprotaso** [comment]
/assign @nak3 
/hold cancel

this should be good - i'll look into flakes in another PR

**Comment by nak3** [comment]
> actually I need to update the GitHub action to not point at my fork

Thank you! LGTM except for the `uses: dprotaso/actions-1/setup-kind@main`

**Comment by dprotaso** [comment]
/hold cancel

@nak3 This should be good now

**Comment by dprotaso** [comment]
I re-ran codecov @ main

**Comment by dprotaso** [comment]
Looks like it worked

**Pull request merged**
